[project]
id = "charthop-webhook"
name = "Charthop Webhook"

[[build.env]]
name = "GOOGLE_RUNTIME"
value = "python"

[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "3.11"

[[build.env]]
name = "GOOGLE_ENTRYPOINT"
value = "gunicorn -b :$PORT main:app"

[[build.buildpacks]]
id = "google.python.runtime"

[[build.buildpacks]]
id = "google.python.dependencies"

[[build.buildpacks]]
id = "google.python.gunicorn"
